apiVersion: v1
kind: Service
metadata:
  labels:
    app: query
  name: sidecar-query
spec:
  ports:
  - name: web
    port: 19090
    protocol: TCP
    targetPort: 19090
  #- name: grpc
  #  port: 10903
  #  protocol: TCP
  #  targetPort: 10903
  selector:
    app: query
  type: NodePort
